Repository openshift/installer-aro-wrapper, pull requests merged in 2023-02, with the labels that each got.

#13 Updating go-toolset version to 1.18.4 from 1.18.4-8
  Dockerfile.aro
Labels: approved, lgtm, ok-to-test

#12 enable accelerated networking
  pkg/installer/deployresources_resources.go
  pkg/installer/generateconfig.go
  pkg/installer/generateconfig_test.go
Labels: approved, lgtm

#16 ARO-1476: Default to OVNKubernetes
  pkg/installer/generateconfig.go
Labels: approved, lgtm, jira/valid-reference

#17 [release-4.10] ARO-1476: Allow user to set NetworkType
  pkg/installer/generateconfig.go
Labels: approved, lgtm, jira/valid-reference
